name: resto_firebase
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_storage: ^11.2.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
